version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: development-docker

services:
  teslo-shop:
    image: rodarte/nestjs-fr-teslo-shop-dev:18e455a
    volumes:
      - ./teslo-shop:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
  teslo-shop-postgres:
    ports:
      - '5432:5432'
    volumes:
      - ./teslo-shop/postgres/dev:/var/lib/postgresql/data
