version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: production-docker

services:
  teslo-shop:
    image: rodarte/nestjs-fr-teslo-shop-prod:3a19300
    ports:
      - '3000:3000'
    environment:
      <<: *common-env-variables
      PORT: 3000
    depends_on:
      - teslo-shop-postgres
  teslo-shop-postgres:
    image: postgres:14.3
    ports:
      - '5432:5432'
    secrets:
      - teslo_shop_postgres_password
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/teslo_shop_postgres_password
      POSTGRES_DB: nestjs-teslo-shop
    volumes:
      - ./teslo-shop/postgres/prod:/var/lib/postgresql/data

secrets:
  teslo_shop_postgres_password:
    file: ./secrets/docker/teslo-shop/postgres-password.txt
