version: '3.4'

x-common-env-variables: &common-env-variables
  NODE_ENV: development-docker

services:
  teslo-shop:
    image: rodarte/nestjs-fr-teslo-shop-dev:3a19300
    volumes:
      - ./teslo-shop:/node/app
      - /node/app/node_modules
    environment:
      <<: *common-env-variables
